### ISSUE TITLE
PLD code

### ISSUE THREAD

**Issue by DFL1973** [rallepalaveev/Prodos-512kB-NVRAM-Drive#1]
Is the PLD source available?

**Comment by rallepalaveev** [comment]
PIN 1 = IOSelect;
PIN 2 = A8;
PIN 3 = A9;
PIN 4 = A0;
PIN 5 = A10;
PIN 6 = DevSel;
PIN 7 = F0;
PIN 8 = RW;
PIN 9 = IOStrobe;
PIN 10 = MemOn;
PIN 11 = A1_sw;
PIN 13 = A2_sw;
PIN 14 = CLK_374;
PIN 15 = OE_374;
PIN 16 = A10_out;
PIN 17 = CE_ROM;
PIN 18 = CE_RAM;
PIN 19 = A8_out;
PIN 20 = A9_out;
PIN 21 = WE;
PIN 22 = WR_STR;
PIN 23 = OE;
OE = !RW;
WE = !(F0 & !RW);
OE_374 = !IOSelect;
WR_STR = IOStrobe # RW;
A8_out = (A8 & IOSelect) # (A1_sw & !IOSelect);
A9_out = A9 # !IOSelect;
A10_out = A10 & IOSelect;
CLK_374 = !(!RW & !DevSel & F0);
CE_ROM = !(!IOSelect # (!(IOStrobe # MemOn) & (RW $ A2_sw)));
CE_RAM = !(!(IOStrobe # MemOn) & !(RW $ A2_sw));

**Comment by StormTrooper** [comment]
I'm also looking for the source or jed file for the GAL

**Comment by rallepalaveev** [comment]
Added.
