### ISSUE TITLE
PO File missing from ProDOS-NVRAM-Drive-512KB_v42.zip

### ISSUE THREAD

**Issue by StormTrooper** [rallepalaveev/Prodos-512kB-NVRAM-Drive#2]
In the readme file it refers to a .PO file but this seems to be missing from the zip file. 

There is a PO file in ProDOS-NVRAM-Drive-512KB_v36.zip but I don't think this is compatiable with newer hardware?

Also is the PLD file available? There was a issue raise for this but I see it's closed. I can't find the file anywhere.

**Comment by rallepalaveev** [comment]
.PO v42 added to zip.

.PO v36 is for fw up to 2.2.

PLD source added.
