### ISSUE TITLE
Unable to get device working - compiling correctly?

### ISSUE THREAD

**Issue by StormTrooper** [rallepalaveev/Prodos-512kB-NVRAM-Drive#3]
I've built one of these devices (HW v2.5) and download NVRAM_Drive_512kB_v2.5.pld which I then compiled for the GAL22V10 using WinCupl. 

I then programmed ProDOS-NVRAM-Drive-512KB_v42.po to a 39SF040
On bootup it seems to start ProDos but then freezes on the below screen with a block (sometimes a M)  on the top left. 

Any idea as to what the issue could be? I've tried swapping out the RAM/GAL/ROM so wondering if there is some other issue. Maybe compile is not working even though it's not giving any compile errors?

![20230530_214204](https://github.com/rallepalaveev/Prodos-512kB-NVRAM-Drive/assets/1429043/0e62cb48-b7f8-491a-bfde-d7317d83ffd2)

**Comment by rallepalaveev** [comment]
Hi, what computer are you testing it on? Best is to try on an Apple IIe. The original Apple II with 16 Saturn card seem to not load ProDOS correctly.

**Comment by rallepalaveev** [comment]
Just thinking of more things to try...
1. Does ProDOS boot normally from a floppy disk?
2. If not, does any ProDOS version boot normally, which one?
3. The version of ProDOS which boots can be put on the card and it should work with it.
4. When ProDOS is loaded from a floppy disk, check if you can read/write files on the card. Copy Plus 8.4 can be used.

**Comment by StormTrooper** [comment]
Thanks for the info. I'll run a few tests and let you know.  I'm running this on a Apple IIe.

I have also built a ProDOS ROM card by tjboldt and this works 100% so I don't think there is any issues with my Apple.

https://github.com/tjboldt/ProDOS-ROM-Drive

**Comment by rallepalaveev** [comment]
I agree, if it is IIe - then all is fine re ProDOS compatibility. I developed the cards on a IIe.

**Comment by StormTrooper** [comment]
GAL22V10 is pin for pin compatible with the ATF22V10C.  As you said initial ProDOS page is loaded so am not sure it could even be  a logic issue. To rule it out can you post your JED file?

**Comment by StormTrooper** [comment]
Found the issue - sill mistake. I tried your JED file and then it started working. Went back to my JED file and it continued to work. Turns out when I first tested it last night it was in slot 3 which caused the issue. I move the card to slot 7 now as per the documentation and it works!

**Comment by rallepalaveev** [comment]
Hi, yes - it should work in any slot as the firmware code is relocatable. However, Slot 3 is special and there might be issues there I guess. I never used it as my computer's AUX slot is opposite Slot 3 and there I have the 80-col card.

Glad it worked!

R.
